export const TRUYENFULL_IO_HOST = 'truyenfull.io'
export const TRUYENF_COM_HOST = 'truyenf.com'
export const STORY_TITLE_CLASSNAME = 'truyen-title'
export const CHAPTER_TITLE_CLASSNAME = 'chapter-title'
export const CHAPTER_CONTENT_CLASSNAME = 'chapter-c'